export const Data = [{
    EventId: '1',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 1',
    Date: '23 May 2020',
    Seats_availabilty: '23',
},
{
    EventId: '2',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 2',
    Date: '24 May 2020',
    Seats_availabilty: '12',
},
{
    EventId: '3',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 3',
    Date: '25 May 2020',
    Seats_availabilty: '0',
},
{
    EventId: '4',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 4',
    Date: '26 May 2020',
    Seats_availabilty: '42',
},
{
    EventId: '5',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 5',
    Date: '27 May 2020',
    Seats_availabilty: '0',
},
{
    EventId: '6',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 6',
    Date: '28 May 2020',
    Seats_availabilty: '25',
},
{
    EventId: '7',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 7',
    Date: '29 May 2020',
    Seats_availabilty: '20',
},
{
    EventId: '8',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 8',
    Date: '30 May 2020',
    Seats_availabilty: '1',
},
{
    EventId: '9',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 9',
    Date: '30 May 2020',
    Seats_availabilty: '0',
},
{
    EventId: '10',
    ImageURL: 'images/event.jpg',
    EventName: 'Event 10',
    Date: '30 May 2020',
    Seats_availabilty: '15',
}
]
